import { createHash } from 'node:crypto';
import { type Kysely, sql } from 'kysely';
import { valueSetToFhirResource } from '../../fhir-value-set';
import { NEW_FIELDS_SNAPSHOT } from './071_facility_form_target';

// Facility registry slice 2 (level/status ValueSets): seeds two ValueSets an operator picks the
// Facility form's Level and Status from — see docs/superpowers/plans/2026-08-04-facility-level-
// status-valuesets.md — and repoints any already-migrated install's Facility form (071 rewrote its
// `schema.fields` to NEW_FIELDS_SNAPSHOT, all free text) at the same two bound-field shapes the
// CURRENT sample ships (packages/forms/src/samples/forms.ts). Migrations never re-run, so a form
// 071 already touched needs this second, narrower rewrite to reach the bound-field shape a FRESH
// install gets straight from the seeder.
//
// ⛔ Every seeded concept's `status` is written UPPERCASE 'ACTIVE'. Downstream `filterConcepts`/
// `listSystemConcepts` compare status case-SENSITIVELY — a lowercase 'active' would not error, it
// would just silently exclude the concept from every activeOnly query. See
// packages/db/src/terminology-admin-store.ts's `listSystemConcepts`.
//
// ⛔ Neither ValueSet's `compose` uses a FHIR `filter` clause — `value-set-expander.ts`'s
// `collectClause` ignores the filter `op` entirely (it only ever compares `op === '='`), so an
// `is-a`-style filter would silently match nothing. Both sets enumerate their concepts explicitly
// via `concept: [...]`, exactly like 014_value_sets.ts's own seeds.

// ---------------------------------------------------------------------------------------------
// Status ValueSet — FHIR's own location-status codes, over FHIR's own CodeSystem.
// ---------------------------------------------------------------------------------------------
const STATUS_SYSTEM = 'http://hl7.org/fhir/location-status';
const STATUS_VS_URL = 'urn:openldr:valueset:location-status';
// NOT `vs-seed-location-status`: 014_value_sets.test.ts scopes an assertion to ids prefixed
// `vs-seed-` specifically because, at the time it was written, only 014 used that prefix (069's
// own seeds deliberately used a bare `vs-<slug>` for the same reason — see that test's comment).
// Reusing `vs-seed-` here would silently inflate 014's "014 seeds exactly six, nothing more" count
// to eight and fail an existing, must-not-weaken test.
const STATUS_VS_ID = 'vs-location-status';
const STATUS_PUBLISHER = 'pub-hl7-fhir';

const STATUS_CONCEPTS: [string, string][] = [
  ['active', 'Active'],
  ['suspended', 'Suspended'],
  ['inactive', 'Inactive'],
];

// A real install's terminology catalog already carries a coding_systems row for this URL — seeded
// (outside any numbered migration) from the bundled FHIR core CodeSystem catalog, shipped as an
// INACTIVE stub with zero concepts, at a random `cs-<uuid>` id (verified against the live dev DB:
// `active: false`, `seeded: true`, `publisher_id: 'pub-hl7-fhir'`). up() flips that row's `active`
// to true rather than inserting a second row for the same url — `coding_systems_url_uq` would
// reject a literal duplicate anyway, but a second differently-cased/slightly-different row is not
// what a unique index catches. A bare test/CI database that never imported that catalog has no such
// row; up() falls back to inserting a minimal one at THIS deterministic id so the ValueSet's system
// is still registered — never colliding with the random uuid a real install's row carries.
const STATUS_CS_FALLBACK_ID = 'cs-openldr-location-status-seed';

// ---------------------------------------------------------------------------------------------
// Level ValueSet — the 63-entry HFR facility-type list, over a DEDICATED new CodeSystem.
// ---------------------------------------------------------------------------------------------
const LEVEL_SYSTEM = 'urn:openldr:cs:facility-type';
const LEVEL_VS_URL = 'urn:openldr:valueset:facility-type';
// Same `vs-seed-` avoidance as STATUS_VS_ID above.
const LEVEL_VS_ID = 'vs-facility-type';
const LEVEL_CS_ID = 'cs-openldr-facility-type';
const LEVEL_PUBLISHER = 'pub-system';

// 63 [code, display] pairs, transcribed VERBATIM from the plan's Appendix (generated by slugifying
// the HFR display strings; verified 63/63 unique codes and 63/63 unique displays there). Displays
// keep the source's inconsistent casing on purpose ('Mobile Dental clinic', 'speech and language
// therapy clinic') — this is the vocabulary as published, not a typo to fix.
const LEVEL_CONCEPTS: [string, string][] = [
  ['dispensary', 'Dispensary'],
  ['health-center', 'Health Center'],
  ['mobile-medical-clinic', 'Mobile Medical Clinic'],
  ['polyclinic', 'PolyClinic'],
  ['super-specialised-clinic', 'Super Specialised Clinic'],
  ['specialised-clinic', 'Specialised Clinic'],
  ['medical-clinic', 'Medical Clinic'],
  ['eye-clinic', 'Eye Clinic'],
  ['basic-dental-clinic', 'Basic Dental Clinic'],
  ['radiology-services-center', 'Radiology Services Center'],
  ['physiotherapy-clinic', 'Physiotherapy Clinic'],
  ['ambulance-and-air-services', 'Ambulance and Air Services'],
  ['ship-services', 'Ship Services'],
  ['optometry-clinic', 'Optometry Clinic'],
  ['specimen-collection-point', 'Specimen Collection Point'],
  ['nursing-home', 'Nursing Home'],
  ['maternity-home', 'Maternity Home'],
  ['maternity-and-nursing-home', 'Maternity and Nursing Home'],
  ['warehouse', 'Warehouse'],
  ['national-hospital', 'National Hospital'],
  ['national-super-specialized-hospital', 'National Super Specialized Hospital'],
  ['zonal-referral-hospital', 'Zonal Referral Hospital'],
  ['regional-referral-hospital', 'Regional Referral Hospital'],
  ['district-hospital', 'District Hospital'],
  ['optical-laboratory', 'Optical Laboratory'],
  ['optical-manufacturing-factory', 'Optical Manufacturing Factory'],
  ['optical-surfacing-unit', 'Optical Surfacing Unit'],
  ['supplying-and-distribution-unit-of-optical', 'Supplying and Distribution unit of Optical'],
  ['hospital-at-zonal-level', 'Hospital at Zonal Level'],
  ['hospital-at-regional-level', 'Hospital at Regional Level'],
  ['hospital-at-district-level', 'Hospital at District Level'],
  ['dental-hospital', 'Dental Hospital'],
  ['dialysis-clinic', 'Dialysis Clinic'],
  ['general-clinic', 'General Clinic'],
  ['specialized-polyclinic', 'Specialized Polyclinic'],
  ['super-specialized-polyclinic', 'Super Specialized Polyclinic'],
  ['comprehensive-dental-clinic', 'Comprehensive Dental Clinic'],
  ['mobile-dental-clinic', 'Mobile Dental clinic'],
  ['level-ia2-dispensary-laboratory', 'Level IA2 (Dispensary Laboratory)'],
  ['level-ia1-health-center-laboratory', 'Level IA1 (Health Center Laboratory)'],
  ['level-iia2-district-laboratory', 'Level IIA2 (District Laboratory)'],
  ['level-iia1-regional-laboratory', 'Level IIA1 (Regional Laboratory)'],
  ['level-iii-multipurpose-health-laboratory', 'Level III Multipurpose Health Laboratory'],
  ['level-iii-single-purpose-health-laboratory', 'Level III Single purpose Health Laboratory'],
  ['dental-laboratory', 'Dental Laboratory'],
  ['prosthetics-and-orthotics-clinic', 'Prosthetics and Orthotics clinic'],
  ['speech-and-language-therapy-clinic', 'speech and language therapy clinic'],
  ['mobile-radiology-and-imaging-centre', 'Mobile Radiology and Imaging Centre'],
  ['occupational-therapy-clinic', 'Occupational Therapy Clinic'],
  ['psychiatric-clinic', 'Psychiatric Clinic'],
  ['diagnostic-centre', 'Diagnostic Centre'],
  ['specialised-dental-clinic', 'Specialised Dental Clinic'],
  ['specialised-eye-clinic', 'Specialised Eye Clinic'],
  ['district-vaccine-store', 'District Vaccine Store'],
  ['specialised-hospital-level-iii', 'Specialised Hospital (Level III)'],
  ['specialised-hospital-level-ii', 'Specialised Hospital (Level II)'],
  ['specialised-hospital-level-i', 'Specialised Hospital (Level I)'],
  ['aesthetic-clinic-level-iii', 'Aesthetic Clinic (Level III)'],
  ['aesthetic-clinic-level-ii', 'Aesthetic Clinic (Level II)'],
  ['aesthetic-clinic-level-i', 'Aesthetic Clinic (Level I)'],
  ['health-post', 'Health Post'],
  ['consultation-clinic', 'Consultation Clinic'],
  ['gym', 'Gym'],
];

// No per-row ownership marker here (there used to be one, stamped into `properties`). Ownership of
// a seeded (system, code) pair is instead decided structurally in down() — see the comment there —
// by which SYSTEM a code belongs to, not by a flag on the row. A marker in `properties` is terminology
// DATA, not migration bookkeeping: it traced onto the terminology sync wire verbatim (serveConceptsPage
// puts `properties` on ConceptWire unmodified and the receiver writes it straight back) and into
// `openldr terminology lookup --json` output, and it wasn't even durable — terms.update() rebuilds
// `properties` via packProps(input), which returns null for a concept carrying none of the five known
// keys, so an operator merely fixing a display in the UI would silently wipe it.
async function insertConcepts(seedDb: Kysely<any>, system: string, concepts: [string, string][]): Promise<void> {
  // Batched as ONE multi-row insert rather than looping an awaited insert per concept — 63+3
  // sequential round trips across every table in this migration was measurably slow enough to tip
  // otherwise-unrelated tests over their 5s timeout when running the whole migrations directory
  // (every test in it calls makeMigratedDb(), which runs every migration including this one). Each
  // row is independently unique, so ON CONFLICT DO NOTHING over the whole statement behaves
  // identically to the per-row loop.
  await seedDb.insertInto('terminology_concepts').values(
    concepts.map(([code, display]) => ({ system, code, display, status: 'ACTIVE', properties: null })) as never,
  ).onConflict((oc) => oc.columns(['system', 'code']).doNothing()).execute();
}

// Unlike 069_result_role_valuesets.ts's seeds — which carry NO expansion, so a missing
// `fhir.change_log` row is harmless (see that file's comment) — these two ValueSets DO carry an
// expansion (`valueSetToFhirResource` is passed the concept list below), so a canonical
// `fhir.fhir_resources` row with no accompanying `change_log` entry would be invisible to the
// incremental projection (`fetchSafeChangeRows` only ever reads `where seq > cursor` on change_log).
// That is precisely the defect that forced an `openldr terminology reproject` backfill for migration
// 014's seeds (see packages/bootstrap/src/seed.ts's AST-interpretation comment) — so, unlike 069,
// up() writes both rows itself here, mirroring the shape fhir-store.ts's writeVersion() writes
// (history first, then change_log — resource_type, id/resource_id, version, op, content_hash, site_id).
// Without the `fhir.resource_history` row, a LATER edit through fhirStore.save() (e.g. an operator
// re-saving/re-expanding this ValueSet from Settings -> Terminology) derives its next version from
// `coalesce(max(resource_history.version), 0) + 1`; with no history row for this id, that computes 1
// again — a second change_log row at version 1 for the same resource, with a different content_hash,
// and `latestSite()`'s `order by version desc limit 1` then picks arbitrarily between the two.
// `fhir.resource_history`'s PK is (resource_type, id, version), so its insert is guarded by a plain
// `onConflict().doNothing()` on that key. `fhir.change_log.seq` is a bare bigserial with no natural
// unique constraint for `onConflict` to key off, so that insert is guarded by an explicit existence
// check instead — a re-run of up() must not append a duplicate entry.
async function seedHistoryAndChangeLog(seedDb: Kysely<any>, id: string, resource: unknown): Promise<void> {
  const serialized = JSON.stringify(resource);
  const contentHashHex = createHash('sha256').update(serialized).digest('hex');

  await seedDb.insertInto('fhir.resource_history').values({
    resource_type: 'ValueSet', id, version: 1, op: 'upsert', resource: serialized,
  } as never).onConflict((oc) => oc.columns(['resource_type', 'id', 'version']).doNothing()).execute();

  const already = await seedDb
    .selectFrom('fhir.change_log')
    .select('seq')
    .where('resource_type', '=', 'ValueSet')
    .where('resource_id', '=', id)
    .executeTakeFirst();
  if (already) return;

  // site_id: null is deliberate, not an oversight — terminology travels the ValueSet/CodeSystem sync
  // channel (`/api/sync/terminology/*`), never the FHIR change_log a lab pushes from, so there is no
  // owning site to stamp. push-worker.ts's M1 guard logs this at ERROR ("missing site_id on safe
  // record; record PERMANENTLY skipped...") for exactly this reason on every enrolled install that
  // runs this migration — that is expected here, not a bug to chase; skipping the push IS the correct
  // outcome for a row that was never meant to travel that channel.
  await seedDb.insertInto('fhir.change_log').values({
    resource_type: 'ValueSet', resource_id: id, version: 1, op: 'upsert', content_hash: contentHashHex, site_id: null,
  } as never).execute();
}

async function seedStatusValueSet(seedDb: Kysely<any>): Promise<void> {
  const existing = await seedDb
    .selectFrom('coding_systems')
    .select(['id', 'active'])
    .where('url', '=', STATUS_SYSTEM)
    .executeTakeFirst();

  if (existing) {
    if (!existing.active) {
      await seedDb.updateTable('coding_systems').set({ active: true } as never).where('url', '=', STATUS_SYSTEM).execute();
    }
    // else: already active — up() has nothing to do, and therefore nothing for down() to reverse.
  } else {
    await seedDb.insertInto('coding_systems').values({
      id: STATUS_CS_FALLBACK_ID, system_code: 'LOCATION-STATUS', system_name: 'LocationStatus',
      url: STATUS_SYSTEM, system_version: null, description: "FHIR's own Location.status codes.",
      active: true, publisher_id: STATUS_PUBLISHER, seeded: true,
    } as never).onConflict((oc) => oc.column('url').doNothing()).execute();
  }

  await insertConcepts(seedDb, STATUS_SYSTEM, STATUS_CONCEPTS);

  const compose = { include: [{ system: STATUS_SYSTEM, concept: STATUS_CONCEPTS.map(([code, display]) => ({ code, display })) }] };
  await seedDb.insertInto('value_sets').values({
    id: STATUS_VS_ID, url: STATUS_VS_URL, version: null, name: 'location-status', title: 'Location Status',
    status: 'active', experimental: false, description: null, compose: JSON.stringify(compose) as never,
    immutable: false, category: null, publisher_id: STATUS_PUBLISHER, expanded_at: sql`now()`,
  } as never).onConflict((oc) => oc.column('url').doNothing()).execute();

  await seedDb.insertInto('valueset_expansions').values(
    STATUS_CONCEPTS.map(([code, display]) => ({ value_set_id: STATUS_VS_ID, system_url: STATUS_SYSTEM, code, display, inactive: false })) as never,
  ).onConflict((oc) => oc.columns(['value_set_id', 'system_url', 'code']).doNothing()).execute();

  const resource = valueSetToFhirResource(
    { id: STATUS_VS_ID, url: STATUS_VS_URL, status: 'active', experimental: false, version: null, name: 'location-status', title: 'Location Status', description: null, compose },
    STATUS_CONCEPTS.map(([code, display]) => ({ system: STATUS_SYSTEM, code, display })),
  );
  // `fhir_resources` was relocated to the `fhir` schema by migration 045 — addressed here as
  // `fhir.fhir_resources`, same as 069_result_role_valuesets.ts (written after that pivot; 014 was
  // written before it and still targets the bare, now-nonexistent, `public.fhir_resources`).
  await seedDb.insertInto('fhir.fhir_resources').values({
    id: STATUS_VS_ID, resource_type: 'ValueSet', resource: JSON.stringify(resource),
  } as never).onConflict((oc) => oc.columns(['resource_type', 'id']).doNothing()).execute();
  await seedHistoryAndChangeLog(seedDb, STATUS_VS_ID, resource);

  await seedDb.insertInto('terminology_systems').values({
    url: STATUS_VS_URL, version: null, kind: 'ValueSet', resource_id: STATUS_VS_ID,
  } as never).onConflict((oc) => oc.column('url').doNothing()).execute();
}

async function seedLevelValueSet(seedDb: Kysely<any>): Promise<void> {
  // A brand-new system — never reused from `urn:openldr:cs:local`. 014's local system is a single
  // flat code space shared across six unrelated seeds and dedups on CODE ALONE; had these 63 codes
  // landed there, any collision with a future local-system code would be silently dropped.
  await seedDb.insertInto('coding_systems').values({
    id: LEVEL_CS_ID, system_code: 'FACILITY-TYPE', system_name: 'OpenLDR Facility Type Codes',
    url: LEVEL_SYSTEM, system_version: null, description: "HFR facility-type codes for the Facility form's Level field.",
    active: true, publisher_id: LEVEL_PUBLISHER, seeded: true,
  } as never).onConflict((oc) => oc.column('url').doNothing()).execute();

  await insertConcepts(seedDb, LEVEL_SYSTEM, LEVEL_CONCEPTS);

  const compose = { include: [{ system: LEVEL_SYSTEM, concept: LEVEL_CONCEPTS.map(([code, display]) => ({ code, display })) }] };
  await seedDb.insertInto('value_sets').values({
    id: LEVEL_VS_ID, url: LEVEL_VS_URL, version: null, name: 'facility-type', title: 'Facility Type',
    status: 'active', experimental: false, description: null, compose: JSON.stringify(compose) as never,
    immutable: false, category: null, publisher_id: LEVEL_PUBLISHER, expanded_at: sql`now()`,
  } as never).onConflict((oc) => oc.column('url').doNothing()).execute();

  await seedDb.insertInto('valueset_expansions').values(
    LEVEL_CONCEPTS.map(([code, display]) => ({ value_set_id: LEVEL_VS_ID, system_url: LEVEL_SYSTEM, code, display, inactive: false })) as never,
  ).onConflict((oc) => oc.columns(['value_set_id', 'system_url', 'code']).doNothing()).execute();

  const resource = valueSetToFhirResource(
    { id: LEVEL_VS_ID, url: LEVEL_VS_URL, status: 'active', experimental: false, version: null, name: 'facility-type', title: 'Facility Type', description: null, compose },
    LEVEL_CONCEPTS.map(([code, display]) => ({ system: LEVEL_SYSTEM, code, display })),
  );
  await seedDb.insertInto('fhir.fhir_resources').values({
    id: LEVEL_VS_ID, resource_type: 'ValueSet', resource: JSON.stringify(resource),
  } as never).onConflict((oc) => oc.columns(['resource_type', 'id']).doNothing()).execute();
  await seedHistoryAndChangeLog(seedDb, LEVEL_VS_ID, resource);

  await seedDb.insertInto('terminology_systems').values({
    url: LEVEL_VS_URL, version: null, kind: 'ValueSet', resource_id: LEVEL_VS_ID,
  } as never).onConflict((oc) => oc.column('url').doNothing()).execute();
}

// ---------------------------------------------------------------------------------------------
// Form repoint: rewrite an already-migrated install's Facility form's `level`/`status` fields to
// the bound shapes the CURRENT sample ships. Inlined literals, not imported from @openldr/forms —
// a migration is a frozen snapshot of one release and must never live-track the moving sample (and
// packages/db must not depend on @openldr/forms, which already depends on packages/db).
// ---------------------------------------------------------------------------------------------
const STATUS_FIELD = {
  id: 'fld-fac-status', fhirPath: 'status', displayLabel: 'Status', description: null,
  fieldType: 'reference', required: true, enabled: true, order: 6,
  cardinality: { min: 1, max: '1' }, apiProperty: 'status',
  valueSetUrl: STATUS_VS_URL,
} as const;

const LEVEL_FIELD = {
  id: 'fld-fac-level', fhirPath: 'physicalType', displayLabel: 'Level', description: null,
  fieldType: 'reference', required: true, enabled: true, order: 7,
  cardinality: { min: 1, max: '1' }, apiProperty: 'level',
  valueSetUrl: LEVEL_VS_URL,
} as const;

// NEW_FIELDS_SNAPSHOT (071) with only its 'status' (index 6) and 'level' (index 7) entries bound
// to the ValueSets seeded above — every other field, and every other property of those two fields
// (id/fhirPath/displayLabel/order/required/cardinality/apiProperty), is untouched. Exported so
// packages/forms/src/samples/forms.test.ts can pin the CURRENT sample against this migration's idea
// of "bound", the same way it already pins against 071's NEW_FIELDS_SNAPSHOT for "new".
export const BOUND_FIELDS_SNAPSHOT: readonly unknown[] = NEW_FIELDS_SNAPSHOT.map((f: any) =>
  f.id === 'fld-fac-status' ? STATUS_FIELD : f.id === 'fld-fac-level' ? LEVEL_FIELD : f,
);

/** Mirrors 071's MARKER_KEY discipline, scoped to just `fields` — 072 never touches target_pages
 *  or status, so there is nothing else to restore. See 071_facility_form_target.ts's MARKER_KEY
 *  doc comment for why a marker (not a heuristic re-derivation) is required: a fresh install seeded
 *  after this release lands on exactly BOUND_FIELDS_SNAPSHOT too, content-identical to a row up()
 *  just repointed. */
const MARKER_KEY = '__migration072';

interface Migration072Marker {
  prevFields: readonly unknown[];
}

async function repointForm(seedDb: Kysely<any>): Promise<void> {
  const rows = await seedDb
    .selectFrom('form_definitions')
    .select(['id', 'schema'])
    .where('name', '=', 'Facility')
    .execute();
  if (rows.length !== 1) return; // none seeded, or ambiguous — never guess which row is "the" one
  const row = rows[0];

  const schema = (typeof row.schema === 'string' ? JSON.parse(row.schema) : row.schema) as Record<string, unknown> | null;
  const fields = schema?.fields;
  if (!Array.isArray(fields) || fields.length === 0) return;

  if (stableStringify(fields) !== stableStringify(NEW_FIELDS_SNAPSHOT)) return; // edited, already bound, or an unknown shape — leave it alone

  const marker: Migration072Marker = { prevFields: fields };
  const nextSchema = { ...(schema ?? {}), fields: BOUND_FIELDS_SNAPSHOT, [MARKER_KEY]: marker };

  await seedDb.updateTable('form_definitions').set({ schema: JSON.stringify(nextSchema) } as never).where('id', '=', row.id).execute();
}

async function unrepointForm(seedDb: Kysely<any>): Promise<void> {
  const rows = await seedDb.selectFrom('form_definitions').select(['id', 'schema']).where('name', '=', 'Facility').execute();
  for (const row of rows) {
    const schema = (typeof row.schema === 'string' ? JSON.parse(row.schema) : row.schema) as Record<string, unknown> | null;
    const marker = schema?.[MARKER_KEY] as Migration072Marker | undefined;
    if (!marker) continue; // never touched by up(), or an operator has since re-saved (which strips unknown keys, dropping the marker)

    const { [MARKER_KEY]: _drop, ...rest } = schema as Record<string, unknown>;
    const prevSchema = { ...rest, fields: marker.prevFields };
    await seedDb.updateTable('form_definitions').set({ schema: JSON.stringify(prevSchema) } as never).where('id', '=', row.id).execute();
  }
}

export async function up(db: Kysely<unknown>): Promise<void> {
  const seedDb = db as Kysely<any>;
  await seedStatusValueSet(seedDb);
  await seedLevelValueSet(seedDb);
  await repointForm(seedDb);
}

export async function down(db: Kysely<unknown>): Promise<void> {
  const seedDb = db as Kysely<any>;
  await unrepointForm(seedDb);

  await seedDb.deleteFrom('terminology_systems').where('url', 'in', [STATUS_VS_URL, LEVEL_VS_URL]).execute();
  await seedDb.deleteFrom('fhir.fhir_resources').where('resource_type', '=', 'ValueSet').where('id', 'in', [STATUS_VS_ID, LEVEL_VS_ID]).execute();
  await seedDb.deleteFrom('valueset_expansions').where('value_set_id', 'in', [STATUS_VS_ID, LEVEL_VS_ID]).execute();
  await seedDb.deleteFrom('value_sets').where('url', 'in', [STATUS_VS_URL, LEVEL_VS_URL]).execute();

  // Ownership is decided structurally, per system — no per-row marker (there used to be one; see
  // insertConcepts()'s comment for why it was removed):
  //
  // - LEVEL_SYSTEM (urn:openldr:cs:facility-type) is a namespace THIS migration created outright —
  //   it never existed before up() ran, so every concept under it is unambiguously ours. Delete by
  //   system, unconditionally.
  // - STATUS_SYSTEM (http://hl7.org/fhir/location-status) is FHIR's own standard CodeSystem — a site
  //   could plausibly have imported the FHIR core CodeSystem bundle separately, landing the same three
  //   codes before this migration ever ran, and up()'s `onConflict().doNothing()` would have silently
  //   skipped inserting over them. There is no way to prove, row by row, which of the (at most) three
  //   codes under this system are "ours" — so down() does not delete ANY of them. Leaving three
  //   standard FHIR codes behind after a rollback harms nothing.
  await seedDb.deleteFrom('terminology_concepts').where('system', '=', LEVEL_SYSTEM).execute();

  // LEVEL_CS_ID is always OUR row (urn:openldr:cs:facility-type never existed before this
  // migration) — unambiguous to delete outright.
  await seedDb.deleteFrom('coding_systems').where('id', '=', LEVEL_CS_ID).execute();

  // STATUS_CS_FALLBACK_ID is only ever OUR row too (the fallback-insert branch of
  // seedStatusValueSet) — safe to delete outright. A PRE-EXISTING stub's `active` flag, by
  // contrast, is deliberately NOT flipped back to false here: coding_systems has no jsonb column
  // to carry a "was this false before up() ran" marker (unlike form_definitions.schema), so there
  // is no way to tell "up() flipped this" apart from "it was already active for an unrelated
  // reason" from the boolean alone. Treating activation of a standard FHIR code system as a
  // one-way administrative action is consistent with the rest of this codebase — no existing
  // migration's down() ever reverts a coding_systems.active flip either.
  await seedDb.deleteFrom('coding_systems').where('id', '=', STATUS_CS_FALLBACK_ID).execute();
}

/** Order-preserving, object-key-order-insensitive deep equality via stable stringification —
 *  copied from 071_facility_form_target.ts (not imported: importing a private helper across
 *  migration files would couple two supposedly-frozen snapshots together). */
function stableStringify(value: unknown): string {
  return JSON.stringify(sortValue(value));
}

function sortValue(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortValue);
  if (!value || typeof value !== 'object') return value;
  return Object.fromEntries(
    Object.entries(value as Record<string, unknown>)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([key, child]) => [key, sortValue(child)]),
  );
}
