import type { ReportDesign } from '@openldr/report-designer';
import { i18nKeyForColumn, i18nKeyForPair } from '@openldr/report-designer/pure';

/**
 * French and Portuguese for the built-in report designs.
 *
 * ⛔ Keyed by the ENGLISH SOURCE TEXT, not by element id. Nine of the ten designs share the same
 * scope panel and footer, so a per-element table would repeat "Reporting period" eight times and
 * let the copies drift apart. `applySeedTranslations` walks each design and turns this into the
 * per-element `i18n` map the renderer reads (`resolveI18n`), so a new seeded design built out of
 * familiar labels is translated the moment it is added, with no extra authoring.
 *
 * A string missing from this table prints English. That is the renderer's documented fallback,
 * not a defect: a partial translation gives a readable page in mixed languages, where treating a
 * missing entry as blank would give a page with holes in it.
 *
 * ⛔ NOT in this table, on purpose:
 * - `R`, `I`, `S` and `%R`. That is the coded susceptibility vocabulary, written the same way in
 *   every language on every AST report. "Translating" it would invent local codes that no
 *   surveillance system reads.
 * - Anything a query returns. Only text an author typed into a design is here.
 *
 * The whole-string keys below carry the exact source, leading spaces included: the clinical
 * report's band caption is indented with spaces rather than a rect, so a translation that trims
 * them moves the text.
 */
export const SEED_DESIGN_TEXT: Record<string, { fr: string; pt: string }> = {
  // Shared chrome — the scope panel and footer on every aggregate report.
  'Reporting period': { fr: 'Période de référence', pt: 'Período de referência' },
  Facility: { fr: 'Établissement', pt: 'Unidade' },
  Metric: { fr: 'Indicateur', pt: 'Indicador' },
  Generated: { fr: 'Généré le', pt: 'Gerado em' },
  'Generated by OpenLDR — figures reflect data available at time of generation.': {
    fr: 'Établi par OpenLDR — les chiffres reflètent les données disponibles au moment de la génération.',
    pt: 'Gerado pelo OpenLDR — os números refletem os dados disponíveis no momento da geração.',
  },

  // Column labels shared across several reports.
  Antibiotic: { fr: 'Antibiotique', pt: 'Antibiótico' },
  Tested: { fr: 'Testés', pt: 'Testados' },
  Specimen: { fr: 'Prélèvement', pt: 'Amostra' },
  'Lab number': { fr: 'N° de laboratoire', pt: 'N.º de laboratório' },
  Month: { fr: 'Mois', pt: 'Mês' },
  Test: { fr: 'Analyse', pt: 'Exame' },
  Total: { fr: 'Total', pt: 'Total' },
  Pathogen: { fr: 'Agent pathogène', pt: 'Agente patogénico' },

  // AMR resistance rate.
  'AMR Resistance Rate': { fr: 'Taux de résistance aux antimicrobiens', pt: 'Taxa de resistência antimicrobiana' },
  'Tested and %R per antibiotic': { fr: 'Testés et %R par antibiotique', pt: 'Testados e %R por antibiótico' },

  // Test volume.
  'Test Volume Over Time': { fr: 'Volume d’analyses dans le temps', pt: 'Volume de exames ao longo do tempo' },
  'Reports per test and month': { fr: 'Rapports par analyse et par mois', pt: 'Relatórios por exame e mês' },
  Count: { fr: 'Nombre', pt: 'Contagem' },

  // Turnaround time.
  'Specimen Turnaround Time': { fr: 'Délai de traitement des prélèvements', pt: 'Tempo de resposta das amostras' },
  'Hours received to reported': { fr: 'Heures de la réception au rendu', pt: 'Horas da receção à emissão' },
  Reports: { fr: 'Rapports', pt: 'Relatórios' },
  'Avg hours': { fr: 'Heures moy.', pt: 'Horas méd.' },
  Min: { fr: 'Min', pt: 'Mín.' },
  Max: { fr: 'Max', pt: 'Máx.' },

  // Patient demographics.
  'Patient Demographics': { fr: 'Démographie des patients', pt: 'Demografia dos pacientes' },
  'As of (YYYY-MM-DD)': { fr: 'Au (AAAA-MM-JJ)', pt: 'Em (AAAA-MM-DD)' },
  'Patients per age band, by sex': { fr: 'Patients par tranche d’âge, selon le sexe', pt: 'Pacientes por faixa etária, por sexo' },
  'Age band': { fr: 'Tranche d’âge', pt: 'Faixa etária' },
  Male: { fr: 'Masculin', pt: 'Masculino' },
  Female: { fr: 'Féminin', pt: 'Feminino' },
  'Other/unknown': { fr: 'Autre/inconnu', pt: 'Outro/desconhecido' },

  // AMR by facility.
  'AMR Resistance by Facility': { fr: 'Résistance aux antimicrobiens par établissement', pt: 'Resistência antimicrobiana por unidade' },
  'Tested and resistant per site': { fr: 'Testés et résistants par site', pt: 'Testados e resistentes por local' },
  Resistant: { fr: 'Résistants', pt: 'Resistentes' },

  // GLASS RIS. "(unknown)" inside the legend is a DATA value the source record carries, so it
  // stays in English in every language — translating it would describe a value that never appears.
  'AMR GLASS RIS (stratified)': { fr: 'RIS GLASS AMR (stratifié)', pt: 'RIS GLASS AMR (estratificado)' },
  'Country code': { fr: 'Code pays', pt: 'Código do país' },
  Year: { fr: 'Année', pt: 'Ano' },
  'Isolate counts by susceptibility result.': {
    fr: 'Nombre d’isolats par résultat de sensibilité.',
    pt: 'Contagem de isolados por resultado de sensibilidade.',
  },
  Gender: { fr: 'Genre', pt: 'Género' },
  Age: { fr: 'Âge', pt: 'Idade' },
  Origin: { fr: 'Origine', pt: 'Origem' },
  'R resistant, I intermediate, S susceptible. AMR: antimicrobial resistance. GLASS: Global Antimicrobial Resistance and Use Surveillance System. (unknown) means the value was not recorded in the source record.': {
    fr: 'R résistant, I intermédiaire, S sensible. AMR : résistance aux antimicrobiens. GLASS : système mondial de surveillance de la résistance aux antimicrobiens et de leur usage. (unknown) signifie que la valeur n’était pas renseignée dans l’enregistrement source.',
    pt: 'R resistente, I intermédio, S sensível. AMR: resistência antimicrobiana. GLASS: Sistema Mundial de Vigilância da Resistência e do Uso de Antimicrobianos. (unknown) significa que o valor não foi registado no registo de origem.',
  },

  // First-isolate summary.
  'AMR First-Isolate Resistance Summary': {
    fr: 'Résumé de la résistance sur premiers isolats',
    pt: 'Resumo da resistência em primeiros isolados',
  },
  'First isolates: tested and %R': { fr: 'Premiers isolats : testés et %R', pt: 'Primeiros isolados: testados e %R' },

  // Cumulative antibiogram.
  'AMR Cumulative Antibiogram': { fr: 'Antibiogramme cumulatif', pt: 'Antibiograma cumulativo' },
  'Percent resistant (%R)': { fr: 'Pourcentage de résistance (%R)', pt: 'Percentagem de resistência (%R)' },
  'The figure in parentheses is the number of isolates tested. A blank cell means no susceptibility result was recorded for that antibiotic against that organism in this period.': {
    fr: 'Le chiffre entre parenthèses est le nombre d’isolats testés. Une cellule vide signifie qu’aucun résultat de sensibilité n’a été enregistré pour cet antibiotique contre cet organisme durant la période.',
    pt: 'O número entre parênteses é o número de isolados testados. Uma célula vazia significa que não foi registado nenhum resultado de sensibilidade para esse antibiótico contra esse organismo neste período.',
  },

  // Clinical microbiology report.
  'LABORATORY REPORT': { fr: 'RAPPORT DE LABORATOIRE', pt: 'RELATÓRIO DE LABORATÓRIO' },
  'MICROBIOLOGY — CULTURE & SENSITIVITY': {
    fr: 'MICROBIOLOGIE — CULTURE ET ANTIBIOGRAMME',
    pt: 'MICROBIOLOGIA — CULTURA E ANTIBIOGRAMA',
  },
  Surname: { fr: 'Nom', pt: 'Apelido' },
  'First name': { fr: 'Prénom', pt: 'Nome próprio' },
  Received: { fr: 'Reçu le', pt: 'Recebido em' },
  Sex: { fr: 'Sexe', pt: 'Sexo' },
  DOB: { fr: 'Naissance', pt: 'Nascimento' },
  Panel: { fr: 'Panel', pt: 'Painel' },
  'Performing lab': { fr: 'Laboratoire exécutant', pt: 'Laboratório executante' },
  'Lab location': { fr: 'Localisation du laboratoire', pt: 'Localização do laboratório' },
  'ORGANISM ISOLATED': { fr: 'ORGANISME ISOLÉ', pt: 'ORGANISMO ISOLADO' },
  Isolate: { fr: 'Isolat', pt: 'Isolado' },
  '   ANTIMICROBIAL SUSCEPTIBILITY': {
    fr: '   SENSIBILITÉ AUX ANTIMICROBIENS',
    pt: '   SENSIBILIDADE AOS ANTIMICROBIANOS',
  },
  Antimicrobial: { fr: 'Antimicrobien', pt: 'Antimicrobiano' },
  Result: { fr: 'Résultat', pt: 'Resultado' },
  'Interpretations reflect the laboratory’s reading at time of testing.': {
    fr: 'Les interprétations reflètent la lecture du laboratoire au moment de l’analyse.',
    pt: 'As interpretações refletem a leitura do laboratório no momento do ensaio.',
  },
  'Authorised by ______________________': {
    fr: 'Autorisé par ______________________',
    pt: 'Autorizado por ______________________',
  },

  // Transmission grid. SIL is the settled abbreviation for a laboratory information system in
  // both languages, so the acronym is translated rather than left as LIS.
  'LIS STAKEHOLDERS UPDATE': {
    fr: 'POINT D’INFORMATION SIL AUX PARTIES PRENANTES',
    pt: 'ATUALIZAÇÃO DO SIL PARA AS PARTES INTERESSADAS',
  },
  'Panel codes': { fr: 'Codes de panel', pt: 'Códigos de painel' },
  Laboratories: { fr: 'Laboratoires', pt: 'Laboratórios' },
  '% of possible lab-days': { fr: '% des jours-laboratoire possibles', pt: '% dos dias-laboratório possíveis' },
  'Busiest day (laboratories)': { fr: 'Jour le plus actif (laboratoires)', pt: 'Dia com mais atividade (laboratórios)' },
  'Silent 10+ working days': { fr: 'Silencieux 10+ jours ouvrés', pt: 'Silenciosos há 10+ dias úteis' },
  'Any Selected-Panel Data Submission by Testing Laboratory': {
    fr: 'Toute transmission de données du panel sélectionné, par laboratoire',
    pt: 'Qualquer envio de dados do painel selecionado, por laboratório',
  },
  'Any Other Test Data Submission, All Laboratories': {
    fr: 'Toute autre transmission de données d’analyses, tous laboratoires',
    pt: 'Qualquer outro envio de dados de exames, todos os laboratórios',
  },
  'Generated by OpenLDR. A filled cell means data arrived that day.': {
    fr: 'Établi par OpenLDR. Une cellule remplie signifie que des données sont arrivées ce jour-là.',
    pt: 'Gerado pelo OpenLDR. Uma célula preenchida significa que chegaram dados nesse dia.',
  },
  'Reviewed by ______________________': {
    fr: 'Revu par ______________________',
    pt: 'Revisto por ______________________',
  },
};

/** The languages this table covers. Ordered so the generated map is stable, which keeps a design's
 *  content fingerprint stable and stops the seeder reporting drift on every boot. */
const LANGS = ['fr', 'pt'] as const;

/** Element kinds whose `text` is prose. Mirrors `TRANSLATABLE_KINDS` in the renderer: a barcode's
 *  `text` is the value it encodes, and translating one produces a symbol that scans wrong. */
const PROSE_KINDS = new Set(['text', 'datetime', 'keyvalue']);

/**
 * A seeded design with its `i18n` map filled in from `SEED_DESIGN_TEXT`.
 *
 * Returns the design UNCHANGED when nothing in it is translatable, so a design outside this table
 * keeps the exact content fingerprint it had before this existed and the seeder does not rewrite
 * it for nothing.
 *
 * A design that already carries an `i18n` map is left alone: an authored map is a deliberate
 * decision and must not be overwritten by a generated one.
 */
export function applySeedTranslations(design: ReportDesign): ReportDesign {
  if (design.i18n) return design;
  const maps: Record<string, Record<string, string>> = {};
  const put = (lang: string, key: string, text: string) => {
    (maps[lang] ??= {})[key] = text;
  };

  for (const page of design.pages) {
    for (const el of page.elements) {
      const tr = (source: string | undefined) => (source ? SEED_DESIGN_TEXT[source] : undefined);

      if (PROSE_KINDS.has(el.kind)) {
        const t = tr(el.text);
        if (t) for (const lang of LANGS) put(lang, el.id, t[lang]);
      }
      for (const c of el.boundColumns ?? []) {
        const t = tr(c.label);
        if (t) for (const lang of LANGS) put(lang, i18nKeyForColumn(el.id, c.key), t[lang]);
      }
      // Static pairs, on an UNBOUND keyvalue panel only — a bound panel's labels are its column
      // labels, handled above. A pair value holding a `{{token}}` is skipped: the seeded ones are
      // nothing but the token, so there are no words in them to translate.
      if (el.kind === 'keyvalue' && !el.dataSource) {
        (el.rows ?? []).forEach((row, i) => {
          const label = tr(row[0]);
          if (label) for (const lang of LANGS) put(lang, i18nKeyForPair(el.id, i, 'label'), label[lang]);
          const value = /\{\{/.test(row[1] ?? '') ? undefined : tr(row[1]);
          if (value) for (const lang of LANGS) put(lang, i18nKeyForPair(el.id, i, 'value'), value[lang]);
        });
      }
    }
  }
  return Object.keys(maps).length === 0 ? design : { ...design, i18n: maps };
}
