/**
 * Display formatting for dates on a rendered report.
 *
 * ⛔ The month names are spelled out here rather than taken from `Intl.DateTimeFormat`, and that is
 * the point of this file. The defect it replaces was `now.toLocaleDateString()` with no locale
 * argument, which let the SERVER'S environment decide what a Ministry document said — the audit
 * read `07/08/2026` and could not tell 7 August from 8 July. Passing an explicit `'en-GB'` narrows
 * that but does not remove it: on a small-icu Node build `en-GB` can fall back to another English
 * locale and reorder the parts. A literal table has nothing left to fall back to.
 */
const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'] as const;

const ISO_DATE = /^(\d{4})-(\d{2})-(\d{2})$/;

/** Days in `month` (1-12) of `year`, by the full Gregorian leap rule. */
function daysInMonth(year: number, month: number): number {
  if (month === 2) return (year % 4 === 0 && year % 100 !== 0) || year % 400 === 0 ? 29 : 28;
  return [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31][month - 1];
}

/**
 * `2026-08-12` → `12 Aug 2026`. **Anything else is returned UNCHANGED.**
 *
 * This is a filter, not a parser. A daterange's `from`/`to` are declared `text` and may hold the
 * `—` an unset parameter renders, or free text, or a date-shaped string that is not a real date.
 *
 * ⛔ No `Date` is constructed. Round-tripping `2026-02-30` through `Date` silently yields
 * `2 Mar 2026`, and a wrong date on a clinical report is worse than an ugly one. `Date` also maps
 * two-digit years onto 1900+, so a validity probe built on `Date.UTC(Number('0026'), …)` would be
 * checking the year 1926.
 */
export function formatDisplayDate(value: string): string {
  const m = ISO_DATE.exec(value);
  if (!m) return value;
  const year = Number(m[1]);
  const month = Number(m[2]);
  const day = Number(m[3]);
  if (month < 1 || month > 12) return value;
  if (day < 1 || day > daysInMonth(year, month)) return value;
  return `${day} ${MONTHS[month - 1]} ${m[1]}`;
}

/**
 * A `Date` → the same display format, read from its **host-local** components.
 *
 * Local, not UTC, on purpose: the report is generated by the lab's own server, so "generated on"
 * means the lab's calendar day. Reading UTC components would make a report generated at 01:00 local
 * claim yesterday's date. The FORMAT is environment-independent; the DAY follows the host zone, and
 * that is correct.
 *
 * `now` is caller-supplied (`render/index.ts`). An invalid `Date` makes `getDate()`/`getMonth()`/
 * `getFullYear()` all `NaN`/`undefined`, which without this guard prints the literal string
 * `NaN undefined NaN` on the page. Degrade to the same em dash `draw.ts`'s `UNSET` renders for a
 * declared-but-unset parameter — the literal is repeated here rather than imported to avoid a
 * circular dependency, since `draw.ts` already imports this module.
 */
export function formatDisplayDateOf(d: Date): string {
  if (Number.isNaN(d.getTime())) return '—';
  return `${d.getDate()} ${MONTHS[d.getMonth()]} ${d.getFullYear()}`;
}
